services:
  - type: web
    name: sjc-app
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    dockerCommand: bash -c "php artisan config:clear && php artisan migrate --force && apache2-foreground"
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_NAME
        value: "St. Joseph's College"
      - key: LOG_CHANNEL
        value: stderr
      - key: CACHE_STORE
        value: file
      - key: SESSION_DRIVER
        value: file
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: sjc-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: sjc-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: sjc-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: sjc-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: sjc-db
          property: password

databases:
  - name: sjc-db
    plan: free
    databaseName: sjc_db
    user: sjc_user
